### ISSUE TITLE
why cloudSpeechRecognizer.listening is always false ? 

### ISSUE THREAD

**Issue by workfel** [evancohen/sonus#14]
Hi !

I'm trying to use your example, but when i debug it the `cloudSpeechRecognizer.listening` is always false. So i can't stream my voice to send it too google cloud.

He can hear the hotword , but the command on `annyang-example.js` can't hear me.

I'm on Mac sierra, i have node 6. I installed sox .
I miss something in installation ? 

Thanks.

**Comment by evancohen** [comment]
+@ashishsc 
The purpose of `listening` is to keep track of streaming within Sonus (so as not to start multiple recognition streams at once). It's not meant to be a property exposed by the library.

There could be a few reasoms that streaming recognition isnt working... Have you:
1) downloaded a keyfile from the Google Cloud console for your project?
2) enabled billing for that project?

**Comment by workfel** [comment]
Hi ! 

Yes i have downloaded the json key from from google console and enabled billing.
But i use the 30 free days , do you think it's that ?

**Comment by evancohen** [comment]
You mentioned that the Annyang example doesn't work, does the vanilla example work? What's the output that you get in the console?

**Comment by evancohen** [comment]
Also, are you sure that the key you created has the appropriate permissions to the API? I have some instructions for this for another project here: https://docs.smart-mirror.io/docs/configuring_voice.html

**Comment by workfel** [comment]
It's works thank you ! I not well enable the billing.


Sorry .
Thx again
