### ISSUE TITLE
Why is google speech needed?

### ISSUE THREAD

**Issue by wcoebergh** [evancohen/sonus#46]
Hello,

I'm curious to why google speech is needed to initialize sonus, while it is advertising to be offline. The main reason I am not using any cloud software for speech is that I don't want a recording device at all time in my house that connects to the internet.

Regards!

**Comment by evancohen** [comment]
Google speech is needed for the *streaming* part of Sonus. In a nutshell:  
- Listen offline for hotword
- Detect hotword
- Stream audio to X cloud recognizer (currently Google is the only one supported, working to get more)
- Stop streaming audio after the end of the utterance.
- Repeat...

Your audio won't be streamed to google unless the hotword is detected, and even then it's only for a single utterance. The object required to stream speech isn't initialized until a hotword is detected, but the gRPC connection to google is created on start to make things simple.

Hope that answers your question 🚀

**Comment by wcoebergh** [comment]
Hi,

Thanks, yes it does answer my question. I thought you just tried to be the offline hotword part! Would it be possible for an implementation of just that?

**Comment by evancohen** [comment]
Totally! Check out Snowboy: https://github.com/Kitt-AI/snowboy

**Comment by wcoebergh** [comment]
Yeah boyyy 🚀 Thanks for the help, keep up the good work!
