### ISSUE TITLE
Sonus not working on v7.9.0

### ISSUE THREAD

**Issue by sharmmoh1983** [evancohen/sonus#58]
Hi 
 I am getting following error while running sonus:
ERROR (Input():snowboy-io.cc:315) Fail to open input file "node_modules/snowboy/resources/common.res"
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (Input():snowboy-io.cc:315) Fail to open input file "node_modules/snowboy/resources/common.res"

Even though binaries are fixed in v7.x as per you comment in older issue reported 
29

**Comment by sharmmoh1983** [comment]
I have updated node to v6.9.1. Still getting same runtime error

**Comment by sharmmoh1983** [comment]
Just one idea... why we are looking for common.res from snowboy  in sonus.js 

We can have it from sonus resources folder to do away with such kind of error

**Comment by sharmmoh1983** [comment]
I tried the above approach and it is working

**Comment by evancohen** [comment]
I didn't want to have people downloading the same file twice, but your mitigation is probably a good idea. I'll patch that this week.

**Comment by sharmmoh1983** [comment]
Can I call register command  on Sonus.annayang directly without using addCommands function

ex:  Sonus.annayang.registerCommand

**Comment by sharmmoh1983** [comment]
Can your build expose registerCommand Function as I need to call this function directly without using add Commands on annayang

**Comment by evancohen** [comment]
It looks like [`snowboy/resources/common.res`](https://github.com/Kitt-AI/snowboy/blob/master/resources/common.res) still exists so I'm not sure why you're seeing this error. The "official" way that you could fix this without modifying the library is to pass in the "actual" path to `common.res` as a part of your sonus config. For example:

``` javascript
const sonus = Sonus.init({ hotwords,  resource: 'some/path/to/common.res'}, speech)
```

Implementation is here: [`index.js#L83`](https://github.com/evancohen/sonus/blob/6a07449f46d366ff96ad41e2a2e8d65a0a46e7a6/index.js#L83)

**Comment by evancohen** [comment]
As for exposing registerCommand, can you file another issue so it can be tracked separately? Please include what you're trying to accomplish, as there may be another way that's currently supported :)
