### ISSUE TITLE
Sonus  hotword is getting detected on any speech and sound

### ISSUE THREAD

**Issue by sharmmoh1983** [evancohen/sonus#62]
Hi 

I am using Sonus.annyang on Raspberry  pi 3 and configured smart mirror as hotword for doing triggering

I had created smart-mirror pmdl also using snowboy site

But is seems many times hotword gets detected even by a sound or any speech in the room

It keeps on happening  and I get to see many enteries  in logs stating hotword detected even though I don't say smart mirror 

sonus.on('hotword', (index, keyword) => {
        console.log("hotword triggered");
        new SoundPlayer().sound(ROOT_DIR  + '/resources/ding.wav');

    });

Some weird behaviour is happening with hotword detection:

**Comment by evancohen** [comment]
This *probably* isn't a Sonus issue. You might want to try [adjusting the sensitivity](https://github.com/evancohen/sonus/blob/master/docs/API.md#custom-hotwords) or re-create the model.

**Comment by sharmmoh1983** [comment]
Sorry ...my bad .There was some issue in my code
