### ISSUE TITLE
resultNoMatch : callback

### ISSUE THREAD

**Issue by sharmmoh1983** [evancohen/sonus#64]
Hi 
I want to have a call back function when there is no match of commands .Is it posiible?

**Comment by sharmmoh1983** [comment]
Does Sonus.annyang.addCommands(commands) supports addition of  resultNoMatch callback

**Comment by evancohen** [comment]
You can use add splat (`*`) as the final command to match all input. https://github.com/TalAter/annyang/blob/master/docs/README.md#examples-7

**Comment by sharmmoh1983** [comment]
Based on your input , I am using splat like the following 
'(*)': function (command) {
			console.log('ha-command',command);
			scope.sendSocketNotification('ha-command', command);
		}
But I am getting folllowing error 
Invalid regular expression: /^*$/: Nothing to repeat

**Comment by evancohen** [comment]
Without the parentheses: 
``` javascript
var command = {
  '*': function (command) {
      console.log('ha-command',command);
      scope.sendSocketNotification('ha-command', command);
}
```

**Comment by sharmmoh1983** [comment]
I have tried this one also but giving same error regarding regular expression

var command = {
  '*': function (command) {
      console.log('ha-command',command);
      scope.sendSocketNotification('ha-command', command);
}

**Comment by sharmmoh1983** [comment]
Actually, the error that I have shared is because of the pattern you have shared

**Comment by sharmmoh1983** [comment]
This seems to be the bug or I am not using it properly
I want have  a mapping for no match command
