### ISSUE TITLE
Stream closed after final-result ? 

### ISSUE THREAD

**Issue by jaumard** [evancohen/sonus#69]
Hey :)

Since the last version I have a strange behavior, I put a Amazon Polly response right after final-result to answer my command/question, the problem is that answer is send into the recognition and send back to final-result witch is wrong because of course this one will not be recognize as a good command.

Did you experience this ? Normally after final-result google speech should be off and wait for a hotword right ?

**Comment by evancohen** [comment]
Do you see the hot word being accidentally being trigger when Poly is speaking?

Are you manually triggering the hot word in your code somewhere?

One work around might be to call `.mute()` while Poly is speaking.

**Comment by jaumard** [comment]
Where can I call `.mute()` ? sonus don't have this method (or I missed it ^^)
I trigger manually the hot word after polly is speaking I'll also check maybe I have a problem there.
But if there a mute method somewhere I'll use it to be safe :)

**Comment by evancohen** [comment]
You may be triggering the hot word before poly stops playing. That'd be my guess. Check the [API docs](https://github.com/evancohen/sonus/blob/master/docs/API.md) for info on `.mute()`

**Comment by evancohen** [comment]
Closing this issue because it is stale.
