### ISSUE TITLE
electron error

### ISSUE THREAD

**Issue by uniotAdmin** [evancohen/sonus#70]
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/node_modules/snowboy/lib/node/binding/Release/**electron-v1.7-linux-arm**/snowboy.node'

![image](https://user-images.githubusercontent.com/33514871/34069381-a0b94cb8-e293-11e7-8e16-2cee42f68283.png)

**Comment by evancohen** [comment]
Check out #15 - that should have the info you need :)

**Comment by uniotAdmin** [comment]
@evancohen 
thank you!
I have run './node_modules/.bin/electron-rebuild --pre-gyp-fix'
We confirmed that the electron-v1.4-linux-arm directory was created in 'node_moduls / snowboy / lib / node / binding / Release'.

However, the error still occurs.
![20171218_184140](https://user-images.githubusercontent.com/33514871/34099551-2998abb0-e423-11e7-877d-061c418ffbf8.png)

**Comment by uniotAdmin** [comment]
![20171218_223505](https://user-images.githubusercontent.com/33514871/34108534-c42e264e-e443-11e7-8a02-bef007cb76ac.png)

**Comment by evancohen** [comment]
Ah, this is for Magic Mirror? You may want to just drop in the .npm config file from Sonus electron prebuilt (liked to in that thread) - you may have to change the version number inside it too.

**Comment by uniotAdmin** [comment]
Is this?
![20171220_223446](https://user-images.githubusercontent.com/33514871/34209576-0a8bfa24-e5d6-11e7-884e-3ce6e5257a2b.png)


I changed this to 3.10.10.
Do I have to do 'npm electron rebuild'?
![20171220_223722](https://user-images.githubusercontent.com/33514871/34209661-70bdc098-e5d6-11e7-95da-27fe5be23340.png)

**Comment by evancohen** [comment]
Not quite, I'm talking about `.npmrc`. For the boilerplate that's here: https://github.com/evancohen/sonus-electron-boilerplate/blob/master/.npmrc
