### ISSUE TITLE
Wrong description:  'speechContext' --> 'speechContexts'

### ISSUE THREAD

**Issue by MrSponti** [evancohen/sonus#83]
Checking the description on  Option: **speechContext**  with the related code in ```index.js``` there seems to me an issue, as the code section use the word 'speechContext'  with ** s** at the end

```
speechContexts: options.speechContexts || null
```
and the description in README use the variable speechContext without **s** at the end

```
speechContext - Array of strings containing words/phrases so that the speech recognizer is more likely to recognize
```

**Comment by evancohen** [comment]
Thanks for pointing this out! I've updated the docs accordingly
