### ISSUE TITLE
snowboy 1.3.0 on some HW-systems does not work, but 1.2.0 does

### ISSUE THREAD

**Issue by GermanBluefox** [evancohen/sonus#96]
Can you set the version of snowboy to "1.2.0" instead of "^1.2.0" till the next 1.3.x version appears.
On some HW platforms the 1.3.1 version does not work and the people must manually force the sonus to use 1.2.0.

**Comment by evancohen** [comment]
The 1.3.1 version has some other issues as well. I'll include this in the next release (shooting for this weekend)

**Comment by evancohen** [comment]
Okay so I did a bit more of a deep dive and I think I have a better solution. I have write access to the snowboy npm package, so I'm going to crate a specific sonus patch that hosts all of the precompiled binaries elsewhere. This way I don't break anyone else, and anyone who wants to use any of my binaries (and avoid building), can.

I just moved so I'm setting up a new dev environment so I can work on this. Sorry it's taking so long!

**Comment by evancohen** [comment]
I've built my own binaries for Snowboy 1.3.1 that are compatible with Node 6-12 and have precompiled binaries for darwin (OSX), x64 (most Linux), and ARM (Pi). All of this is included with the most recent version of Sonus (v1.0.2).

**Comment by GermanBluefox** [comment]
Very strange:
![image](https://user-images.githubusercontent.com/4582016/58758855-0de4ee00-8522-11e9-9a08-56659c875a04.png)

**Comment by evancohen** [comment]
How odd... Fixed in `v1.0.3`

**Comment by evancohen** [comment]
Closing this because this has been fixed
